"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """\
$hostname:$username\
(\
    at \
    $directory\
)\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$cmd_duration\
"""

add_newline = false

[hostname]
style = "bold sky"
format = '[$hostname](fg:$style)'
ssh_only=false

[username]
style_user = "bold sapphire"
format = '[$user](fg:$style) '
disabled = false
show_always = true

[directory]
style = "bold lavender"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[cmd_duration]
style = "bold yellow"
format = "took [ $duration]($style) "

[git_branch]
format = "via [$symbol$branch]($style) "
style = "bold mauve"
symbol = " "

[git_status]
style = "bold flamingo"

[git_commit]
format = '[\(#$hash$tag\)]($style) '
style = "bold teal"
tag_disabled = false
only_detached = true
tag_symbol = ' @'

[git_metrics]
added_style = 'bold teal'
deleted_style = 'bold flamingo'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
